name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build project
        run: ./gradlew clean shadowJar

      - name: Upload jar to server via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --progress
          path: build/libs/androidkrdbot-1.0-all.jar
          remote_path: /opt/beriakrd/beriakrd/androidkrdbot.jar
          remote_host: 82.146.46.74
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart service on server
        uses: appleboy/ssh-action@master
        with:
          host: 82.146.46.74
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl stop beriakrd
            systemctl start beriakrd
